local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "telescope Find Files" })
vim.keymap.set('n', '<leader>fg', builtin.git_files, { desc = "telescope Find Git" })
vim.keymap.set('n', '<leader>fs', builtin.live_grep, { desc = "telescope Find String" })
vim.keymap.set('n', '<leader>fk', builtin.keymaps, { desc = "telescope Find Keymaps" })
vim.keymap.set("n", "<Leader>fsb", builtin.current_buffer_fuzzy_find, { desc = "telescope Find String in Buffer" })
vim.keymap.set("n", "<Leader>fb", builtin.buffers, { desc = "telescope Find Buffer" })
